import assert from 'node:assert/strict';
import worker, {routes, PUBLIC_OWNER, LEGACY_OWNER, validRange} from './_worker.js';
import snapshot from './config-snapshot.js';
let calls=[];
const origin='https://preview.example';
const json=x=>new Response(JSON.stringify(x),{headers:{'Content-Type':'application/json'}});
const range=(start=0,end=1023,total=2048)=>new Response(new Uint8Array(end-start+1),{status:206,headers:{
  'Content-Range':`bytes ${start}-${end}/${total}`,'Content-Length':String(end-start+1),'Accept-Ranges':'bytes'}});
function mock(fn) {calls=[];globalThis.fetch=async(url,opts)=>{calls.push({url,opts});return fn(url,opts);};}
const request=(path,options={})=>worker.fetch(new Request(origin+path,options));
let checks=0;
function ok(value,why){checks++;assert.ok(value,why);}
ok(routes('/cn_js_delta.zip')[0].includes(PUBLIC_OWNER),'public first');
ok(routes('/cn_js_delta.zip')[1].includes(LEGACY_OWNER),'emergency retained');
ok(routes('/unexpected.zip').length===0,'allowlist');
mock(()=>{throw new Error('unexpected network');});
ok((await request('/health.json')).status===200,'health');
ok((await request('/anything')).status===404,'unknown path');
ok((await request('/cn_js_delta.zip',{method:'POST'})).status===405,'method restriction');
ok(calls.length===0,'no unknown upstream');
mock(()=>range());
let response=await request('/cn_js_delta.zip',{headers:{Range:'bytes=0-1023',Authorization:'secret-test',Cookie:'secret-test'}});
ok(response.status===206,'valid public range');
ok(response.headers.get('X-Release-Authority')===PUBLIC_OWNER,'actual authority');
ok((await response.arrayBuffer()).byteLength===1024,'range bytes');
ok(calls.length===1 && !calls[0].opts.headers.has('Authorization') && !calls[0].opts.headers.has('Cookie'),'no private credentials or needless legacy call');
mock(url=>url.includes(PUBLIC_OWNER)?new Response('private',{status:404}):range());
response=await request('/cn_js_delta.zip',{headers:{Range:'bytes=0-1023'}});
ok(response.status===206 && response.headers.get('X-Release-Authority')===LEGACY_OWNER && calls.length===2,'one emergency recovery');
mock(()=>new Response('private',{status:404}));
response=await request('/cn_js_delta.zip');
ok(response.status===502 && calls.length===2,'all failed terminates');
mock(()=>new Response('<html>sign in</html>'));
response=await request('/legacy/config.json');
ok(response.headers.get('X-Release-Authority')==='verified-independent-snapshot','config survives both upstreams');
ok((await response.json()).client.sha256===snapshot.client.sha256 && calls.length===2,'independent verified config identity');
mock(()=>json(snapshot));
response=await request('/legacy/config.json',{method:'HEAD'});
ok(response.status===200 && (await response.text())==='' && calls.length===1,'HEAD config validates via bounded GET');
mock(url=>url.includes(PUBLIC_OWNER)?new Response(new Uint8Array(2048)):range());
ok((await request('/cn_js_delta.zip',{headers:{Range:'bytes=0-1023'}})).status===206 && calls.length===2,'ignored range falls back');
mock(()=>range(1,1024));
ok((await request('/cn_js_delta.zip',{headers:{Range:'bytes=0-1023'}})).status===502,'wrong range rejected');
ok(validRange('bytes=-1024',range(1024,2047)),'suffix range');
ok(validRange('bytes=1024-',range(1024,2047)),'open range');
mock(url=>new Response(null,{status:302,headers:{Location:url}}));
ok((await request('/cn_js_delta.zip')).status===502 && calls.length===2,'redirect cycle bounded');
mock(()=>new Response(null,{status:302,headers:{Location:'https://edgeone.assets.magireco.top/cn_js_delta.zip'}}));
ok((await request('/cn_js_delta.zip')).status===502 && calls.length===2,'no CDN recursion');
mock(()=>new Response(null,{status:302,headers:{Location:origin+'/cn_js_delta.zip'}}));
ok((await request('/cn_js_delta.zip')).status===502 && calls.length===2,'no self recursion');
mock(()=>new Response(null,{status:302,headers:{Location:'http://github.com/file'}}));
ok((await request('/cn_js_delta.zip')).status===502,'no downgrade redirect');
mock(()=>json({...snapshot,client:{...snapshot.client,sha256:'0'.repeat(64)}}));
response=await request('/legacy/config.json');
ok(response.headers.get('X-Release-Authority')==='verified-independent-snapshot','same version identity conflict rejected');
mock((_url,opts)=>new Promise((_resolve,reject)=>opts.signal.addEventListener('abort',()=>reject(new Error('timeout')))));
const start=Date.now();response=await request('/legacy/config.json');
ok(response.status===200 && calls.length===2 && Date.now()-start<5000,'metadata total budget below client budget');
console.log(`PASS ${checks} worker migration assertions; source failure, independent config, bounded timeout, streaming and range semantics`);
