#!/usr/bin/env python3
"""Rebuild the v26 machine/LLM provenance and human-review inventory.

The script is deliberately read-only with respect to product translations.  It
only writes deterministic audit artifacts under
``magica/i18n_audit/release_v26_authority/machine_translation_review``.  The
inventory reconciles pass8/pass15 history, the final product dictionaries,
Pass18 authority corrections, the four migrated maintenance tables, and the
native ``engine_i18n.tsv`` runtime table.
"""

from __future__ import annotations

import csv
import gzip
import hashlib
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


PRODUCT = Path(__file__).resolve().parent.parent
ROOT = PRODUCT.parents[1]
LIBS = PRODUCT / "magica" / "js" / "libs"
AUDIT = PRODUCT / "magica" / "i18n_audit"
HERE = AUDIT / "release_v26_authority" / "machine_translation_review"
BUNDLED_INPUTS = HERE / "inputs"
PASS8_RECON = BUNDLED_INPUTS / "pass8_field_provenance_reconstructed.tsv.gz"
PASS8_PROV = BUNDLED_INPUTS / "pass8_final_provenance.tsv.gz"
WIKI_CHARACTERS = BUNDLED_INPUTS / "wiki_characters.json.gz"
WIKI_MEMORIA_EXTRACT = BUNDLED_INPUTS / "wiki_memoria_battle_miss_extract.json"
LEGACY_BATTLE_DECISIONS = BUNDLED_INPUTS / "legacy_battle_runtime_miss_audit_8.tsv"
LEGACY_BATTLE_INVENTORY = BUNDLED_INPUTS / "legacy_battle_runtime_miss_inventory_20.tsv"
SOURCE_SNAPSHOT = BUNDLED_INPUTS / "source_snapshot.json"
RESIDUAL = AUDIT / "wiki_authority_pass15_final" / "remaining_residual_8959.tsv"
PASS9_DOPPEL = AUDIT / "wiki_authority_pass9" / "doppel_equivalence_report.tsv"
PASS9_APPLIED = AUDIT / "wiki_authority_pass9" / "applied_wiki_proposals.tsv"
RELEASE_CHECKLIST = AUDIT / "release_v26_authority" / "manual_review_checklist.tsv"
PASS18 = AUDIT / "release_v26_authority" / "pass18_authority_corrections.tsv"
ENGINE_OFFICIAL = AUDIT / "release_v26_authority" / "pass18_engine_official_additions.tsv"
PASS18_BASELINE = AUDIT / "release_v26_authority" / "pass18_baseline.json"
# Committer date of pass18_baseline.baseline_head, deliberately fixed so a
# later commit or detached checkout cannot change generated bytes.
AUDIT_EPOCH = "2026-08-09T22:46:21+08:00"

# Closed classification of the 53 legacy frontend rows whose offline candidate
# column was empty at the audit baseline.  Keys are stable source keys from input-provenance.tsv, so
# this never guesses identity from script/language shape.  The decisions were
# established by exact current-product-node audit: 18 source strings are absent
# at runtime, 33 visible strings are compatible Chinese identities, one is
# punctuation, and one has an official-CN exact path/DOM match.
FRONTEND_EMPTY_53_DECISIONS = {
    # Exact source string is absent from current runtime nodes: not a backlog.
    **{key: "runtime-absent/not-backlog" for key in (
        "global:139349ae2024c7b0cb66", "global:1653151accee8a673eb5",
        "global:17fc4a0d39f616373959", "global:1d80f6e84eb88218b3cf",
        "global:250558ed3152ec3e23ef", "global:3bc18cfd7f105b5436bb",
        "global:54936347233a66e46f05", "global:7a019de4df4cdb2f3087",
        "global:7f1aadb517eb8109d02d", "global:8b3a3f2114a17bf13859",
        "global:8ddcf27b4dac793d6bd3", "global:c08429a0618bb2fc1a7d",
        "global:c32cf7571e38a30a7ec0", "global:cd3b13999120d21b32fa",
        "global:d12aaa6b8295cd6f21ac", "global:e969459d2dfe755ea748",
        "global:f10bbb4d2dc49ec5d0ab", "global:f649706b08b5e03ee2f4",
    )},
    # Exact runtime nodes are visible Chinese-compatible identities.
    **{key: "visible-cn-compatible-identity" for key in (
        "global:0a9105b64231be7ff6b5", "global:0ba4a522d61b690bc808",
        "global:21adedb16f095c1c9dbe", "global:247f96db649ef7bc8158",
        "global:385dc40306774957d51b", "global:504d9cf3acd3e8aa21f7",
        "global:58c5363bbc8e8c7801b3", "global:5a3aa9c3233df5ca2fab",
        "global:5e10466af9402b5612fc", "global:609b244eeafebab0b919",
        "global:6665ac4ca7f216509cba", "global:6ab22b863490d365d46b",
        "global:6f23b8f870b39941382c", "global:79ce7c7e749732a59a8c",
        "global:859902e249af102fa272", "global:8faf1f2557511c7ae002",
        "global:99a2c6f00139f2983e4f", "global:9ab37a2a780884c94afd",
        "global:a75982d2f551033552a5", "global:b4a29cce993cfaf89d59",
        "global:be8694bf471ae99b2d3f", "global:bf7823c56d97233cbf82",
        "global:caf32677d62cc4340ec2", "global:cf129929e3e69ee01829",
        "global:d0da207c16280c478172", "global:d7b6359b08d443ff0031",
        "global:d902c1b1fa4aaad56527", "global:dee3a60702bf6f8a6387",
        "global:e10c0e0d483296cdb83c", "global:ea06d7d1b29b6d8f8e19",
        "global:ed6c8a6903b72b7ffd47", "global:f555fa8469649c51c0dd",
        "global:ffcefb10562cd485531a",
    )},
    # Visible punctuation identity.
    "global:cb5cfa0c3e59fe868f85": "identity-punctuation",
    # Official CN exact path/DOM match for 属性相性 -> 属性克制.
    "global:6ec4009aee4bddf7aa31": "official-cn-exact-path-dom-match",
}
FRONTEND_EMPTY_53_EVIDENCE = {
    "outputs/frontend_empty_53_audit_20260812/semantic_product_hits.json": (
        "a8d66dcdec688e4baa14071950764802ef696e0d6ea6133ab5709e5dff4c4959"
    ),
    "outputs/frontend_empty_53_closure_20260812T044510Z/items.tsv": (
        "5388304f6acf4a610303e335eda6b1e598e6842ded901b1a502f39d2aa05bfe3"
    ),
    "outputs/frontend_empty_53_closure_20260812T044510Z/summary.json": (
        "b3b2a1e145b7efa3015488b4773d691651a2782636d98d433a9d90c1dc1d8f0e"
    ),
    "official-cn-static/magica/template/formation/FormationQuest.html": (
        "8a73978062da1662bb7405d93ca37ef4e924b8a0b14bd66a56237e6ea8480f8d"
    ),
}


LIST_KEYS = {
    "cardList": ("cardId", "id"),
    "chapterList": ("chapterId", "id"),
    "charaList": ("id", "charaNo"),
    "charaMessageList": ("charaNo_messageId",),
    "doppelList": ("id",),
    "enemyList": ("enemyId", "id"),
    "eventList": ("eventId", "id"),
    "eventStoryList": ("storyIds",),
    "formationSheetList": ("formationSheetId", "id"),
    "giftList": ("id", "giftId"),
    "itemList": ("itemCode", "id", "itemId"),
    "live2dList": ("charaId_live2dId",),
    "patrolAreaList": ("patrolAreaId", "id"),
    "pieceList": ("pieceId", "id"),
    "sectionList": ("sectionId", "id"),
    "shopItemList": ("shopItemId", "id"),
}


MASTER_FIELDS = [
    "record_id",
    "component",
    "scope",
    "file",
    "stable_key_or_line",
    "field",
    # Canonical, user-facing review columns.  The more detailed historical
    # columns below are retained for backwards-compatible filtering.
    "original_text",
    "current_cn",
    "suggested_cn",
    "product_or_reference_location",
    "source_tier",
    "source_bucket",
    "evidence_path_or_key",
    "machine_translated",
    "confidence",
    "review_status",
    "japanese_or_source_original",
    "missing_original_reason",
    "provenance_class",
    "source_stage",
    "source_batch",
    "source_author",
    "is_machine_translation",
    "runtime_consumed",
    "highest_authority_tier",
    "highest_authority_match",
    "authority_status",
    "risk",
    "issue_type",
    "manual_review_status",
    "evidence",
    "notes",
]


def read_tsv(path: Path) -> list[dict[str, str]]:
    if path.suffix == ".gz":
        with gzip.open(path, "rt", encoding="utf-8-sig", newline="") as fh:
            return list(csv.DictReader(fh, delimiter="\t"))
    with path.open("r", encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def write_tsv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(
            fh, fieldnames=fields, delimiter="\t", lineterminator="\n", extrasaction="ignore"
        )
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, value: Any) -> None:
    # Pin LF explicitly on Windows so the audited byte hashes are identical to
    # the Git tree produced under `.gitattributes` (`text eol=lf`).  Relying on
    # Path.write_text's platform default would materialize CRLF in the worktree
    # and make SHA256SUMS stale as soon as Git normalizes the file.
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def read_json(path: Path) -> Any:
    if path.suffix == ".gz":
        with gzip.open(path, "rt", encoding="utf-8-sig") as fh:
            return json.load(fh)
    return json.loads(path.read_text(encoding="utf-8-sig"))


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def relative_display(path: Path) -> str:
    """Return a stable repository/workspace-relative evidence path."""

    try:
        return path.resolve().relative_to(PRODUCT.resolve()).as_posix()
    except ValueError:
        pass
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return str(path)


def product_content_snapshot() -> tuple[int, str]:
    """Hash stable product and maintenance inputs without generated reports."""

    archive_suffixes = {".zip", ".7z", ".tar", ".gz", ".apk"}
    stable_top_dirs = {
        ".github",
        "configures",
        "i18n",
        "madomagi",
        "magica",
        "manifests",
        "scripts",
        "tools",
    }
    stable_magica_dirs = {"css", "fonts", "js", "resource", "template"}
    stable_root_files = {
        ".gitattributes",
        ".gitignore",
        "asset_main_cn.json",
        "Build_JS_Injector.py",
        "README.md",
        "url_map.json",
        "version_js_new.json",
        "version_scenario_new.json",
    }
    excluded_i18n_files = {"migration-source-summary.json", "uiTextList.json"}
    paths: list[Path] = []
    for path in PRODUCT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(PRODUCT)
        if len(rel.parts) == 1 and rel.name not in stable_root_files:
            # Root-level build reports, package hashes, and temporary files are
            # outputs rather than stable product/maintenance inputs.
            continue
        if len(rel.parts) > 1 and rel.parts[0] not in stable_top_dirs:
            # original_source and any local/output tree are source archives,
            # not current product or maintenance inputs.
            continue
        if rel == Path(".git") or ".git" in rel.parts or "__pycache__" in rel.parts:
            continue
        if path.suffix == ".pyc" or path.suffix.lower() in archive_suffixes:
            continue
        if len(rel.parts) >= 2 and rel.parts[:2] in {
            ("magica", "i18n_audit"),
            ("magica", "research"),
            ("i18n", "generated"),
        }:
            # Audit/research trees and generated provenance are independently
            # hashed inputs or outputs, never part of this aggregate.
            continue
        if rel.parts[0] == "madomagi" and rel.as_posix() != "madomagi/engine_i18n.tsv":
            # The JS update carries only the native UI table.  The large
            # scenario/resource tree is a separate product and must not make
            # this audit snapshot depend on unrelated content.
            continue
        if (
            rel.parts[0] == "magica"
            and (len(rel.parts) < 2 or rel.parts[1] not in stable_magica_dirs)
        ):
            # Restrict the product half of the aggregate to the exact roots
            # packaged by the JS updater; audit/research/report trees are
            # independently hashed inputs or generated outputs.
            continue
        if rel.parts[0] == "i18n" and path.name in excluded_i18n_files:
            continue
        paths.append(path)
    paths.sort(key=lambda path: path.relative_to(PRODUCT).as_posix())
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.relative_to(PRODUCT).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(bytes.fromhex(sha256(path)))
        digest.update(b"\n")
    return len(paths), digest.hexdigest()


def finalize_review_columns(row: dict[str, str]) -> None:
    """Populate the canonical comparison columns for one master row."""

    row["original_text"] = row.get("japanese_or_source_original", "")
    location = f"{row.get('file', '')}#{row.get('stable_key_or_line', '')}"
    if row.get("field"):
        location += f"/{row['field']}"
    row["product_or_reference_location"] = location
    row["source_tier"] = row.get("highest_authority_tier", "") or row.get(
        "provenance_class", "unknown"
    )
    classifier = " ".join(
        (
            row.get("source_tier", ""),
            row.get("provenance_class", ""),
            row.get("source_batch", ""),
        )
    ).lower()
    tier = row.get("source_tier", "").lower()
    if (
        "root-personal" in classifier
        or "root_personal" in classifier
        or "root_translat" in classifier
    ):
        row["source_bucket"] = "new-root-human"
    elif tier.startswith("wiki") or tier.startswith("2_") or tier.startswith("第二权威"):
        row["source_bucket"] = "wiki"
    elif "official" in classifier or "1_" in classifier:
        row["source_bucket"] = "official"
    elif "wiki" in classifier or "2_" in classifier or "第二权威" in classifier:
        row["source_bucket"] = "wiki"
    elif "legacy" in classifier or "kimi" in classifier or "claude" in classifier:
        row["source_bucket"] = "legacy-ai"
    else:
        row["source_bucket"] = "unknown"
    row["evidence_path_or_key"] = row.get("evidence", "")
    machine_detail = row.get("is_machine_translation", "unknown")
    if machine_detail == "false" or machine_detail.startswith("false;"):
        row["machine_translated"] = "false"
    elif machine_detail == "historical_llm_or_other_replaced":
        # This flag describes the final/current Chinese candidate.  The
        # historical model bucket remains visible in is_machine_translation.
        row["machine_translated"] = "false"
    elif machine_detail.startswith("ai_assisted"):
        row["machine_translated"] = "ai-assisted-unverified"
    else:
        row["machine_translated"] = "unknown"
    row["review_status"] = row.get("manual_review_status", "") or "needs-human-review"


def pass18_index() -> dict[tuple[str, str, str], dict[str, str]]:
    rows = read_tsv(PASS18)
    result: dict[tuple[str, str, str], dict[str, str]] = {}
    for row in rows:
        key = (Path(row["file"]).name, row["stable_key"], row["field"])
        if key in result:
            raise AssertionError(f"duplicate Pass18 target: {key}")
        result[key] = row
    return result


def json_scalar(text: str) -> Any:
    if not text:
        return ""
    try:
        return json.loads(text)
    except Exception:
        return text


def stable_key(base: str, obj: dict[str, Any]) -> str:
    if base == "charaMessageList":
        return f"{obj.get('charaNo', '')}|{obj.get('messageId', '')}"
    if base == "live2dList":
        return f"{obj.get('charaId', '')}|{obj.get('live2dId', '')}"
    if base == "eventStoryList":
        value = obj.get("storyIds", "")
        return json.dumps(value, ensure_ascii=False, separators=(",", ":")) if isinstance(value, list) else str(value)
    for field in LIST_KEYS.get(base, ()):
        if field in obj:
            return str(obj[field])
    return ""


class Dictionaries:
    def __init__(self, folder: Path):
        self.folder = folder
        self.data: dict[str, Any] = {}
        self.index: dict[str, dict[str, dict[str, Any]]] = {}

    def load(self, filename: str) -> Any:
        if filename not in self.data:
            self.data[filename] = json.loads(
                (self.folder / filename).read_text(encoding="utf-8-sig")
            )
        return self.data[filename]

    def indexed(self, filename: str) -> dict[str, dict[str, Any]]:
        if filename in self.index:
            return self.index[filename]
        data = self.load(filename)
        if isinstance(data, dict):
            result = {str(k): v for k, v in data.items() if isinstance(v, dict)}
        else:
            base = Path(filename).stem
            result = {}
            for item in data:
                if isinstance(item, dict):
                    result[stable_key(base, item)] = item
        self.index[filename] = result
        return result

    def value(self, filename: str, key: str, field: str, fallback: str = "") -> str:
        obj = self.indexed(filename).get(str(key), {})
        value = obj.get(field, fallback) if isinstance(obj, dict) else fallback
        if value is None:
            return ""
        if isinstance(value, str):
            return value
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))

    def checklist_target(self, row: dict[str, str]) -> tuple[str, str, str] | None:
        filename = Path(row["file"]).name
        if filename not in {p.name for p in self.folder.glob("*.json")}:
            return None
        data = self.load(filename)
        raw = row["key_or_line"]
        parts = [x for x in raw.split("/") if x]
        if not parts:
            return None
        if isinstance(data, list) and raw.startswith("/") and parts[0].isdigit():
            index = int(parts[0])
            if index >= len(data) or not isinstance(data[index], dict):
                return None
            key = stable_key(Path(filename).stem, data[index])
        else:
            key = parts[0]
        return filename, key, row["field"]


def authority_check(row: dict[str, str]) -> bool:
    tier = row.get("source_tier", "")
    return tier.startswith("1_") or tier.startswith("2_") or tier.startswith("第二权威")


def risk_for(field: str, current: str, scope: str, category: str = "") -> str:
    if scope == "static_js_html":
        if "production" in category or "translation" in category or len(current) >= 80:
            return "high"
        return "medium"
    if field in {
        "name",
        "title",
        "charaName",
        "cardName",
        "pieceName",
        "parameter",
        "kana",
        "school",
        "outline",
        "description",
        "message",
    }:
        return "high"
    if field in {"shortDescription", "areaDetailName"}:
        return "medium"
    return "low"


def issue_for(field: str, current: str) -> str:
    if field in {"name", "title", "charaName", "cardName", "pieceName", "parameter", "kana", "school"}:
        return "unverified_llm_or_other_proper_name"
    if field in {"description", "outline", "message"} or len(current) >= 80:
        return "unverified_llm_or_other_narrative"
    return "unverified_llm_or_other_structured_or_short_text"


def build_checklist_overlays(dicts: Dictionaries) -> tuple[dict[tuple[str, str, str], dict[str, str]], list[dict[str, str]]]:
    overlays: dict[tuple[str, str, str], dict[str, str]] = {}
    static_rows: list[dict[str, str]] = []
    for row in read_tsv(RELEASE_CHECKLIST):
        if Path(row["file"]).suffix.lower() != ".json":
            static_rows.append(row)
            continue
        target = dicts.checklist_target(row)
        if target:
            overlays[target] = row
    return overlays, static_rows


def normalized_linebreaks(text: str) -> str:
    return text.replace("\\n", "\n").replace("\r\n", "\n")


def source_author_for_batch(batch: str) -> str:
    if "kimi" in batch:
        return "Kimi AI-assisted batch label; per-row human author not proven"
    if "claude" in batch:
        return "Claude AI-assisted batch label; per-row human author not proven"
    if batch == "legacy-unverified-mixed-patch":
        return "unknown mixed human/model authorship"
    if batch.startswith("wiki-"):
        return "HiiragiNemu/magireco-wiki-data contributors"
    return "individual author not recorded"


def append_migrated_i18n_and_engine(master: list[dict[str, str]]) -> dict[str, int]:
    provenance_path = PRODUCT / "i18n" / "generated" / "input-provenance.tsv"
    provenance = read_tsv(provenance_path)
    counts = Counter()
    for source in provenance:
        source_file = source["source_file"]
        if source_file == "i18n/frontend-strings.tsv":
            if source["key"] in FRONTEND_EMPTY_53_DECISIONS:
                counts["frontend_empty_53_audited_cohort"] += 1
                continue
            if source["status"] != "present" or not source["candidate_cn"]:
                raise AssertionError(
                    f"unclassified empty frontend candidate: {source['key']} "
                    f"{source['source_text']!r}"
                )
            component = "frontend_ai_assisted_translated"
            scope = "frontend_i18n_input"
        elif source_file == "i18n/overrides.tsv":
            component = "overrides_unverified_mixed"
            scope = "frontend_i18n_override"
        elif source_file == "i18n/fragments.tsv":
            component = "fragments_unverified_mixed"
            scope = "frontend_i18n_fragment"
        else:
            continue
        counts[component] += 1
        batch = source["source_batch"]
        master.append(
            {
                "record_id": "",
                "component": component,
                "scope": scope,
                "file": source_file,
                "stable_key_or_line": source["candidate_id"],
                "field": "candidate_cn",
                "japanese_or_source_original": source["source_text"],
                "missing_original_reason": "",
                "current_cn": source["candidate_cn"],
                "provenance_class": source["authority"],
                "source_stage": source["scope"],
                "source_batch": batch,
                "source_author": source_author_for_batch(batch),
                "is_machine_translation": "ai_assisted_batch_unverified_per_row" if source_file.endswith("frontend-strings.tsv") else "unknown_mixed_human_model",
                "confidence": "low",
                "runtime_consumed": "false; offline inputs are not consumed by Actions/Build_JS/runtime",
                "highest_authority_tier": "legacy_unverified_ai_assisted",
                "highest_authority_match": "",
                "authority_status": "no_per_entry_official_or_wiki_pair",
                "risk": "high" if source["scope"] in {"fragment", "override"} else "medium",
                "issue_type": "legacy_ai_assisted_or_mixed_i18n_input",
                "suggested_cn": "needs-review/root-translation-required",
                "manual_review_status": "pending",
                "review_status": "needs-human-review",
                "evidence": f"{relative_display(provenance_path)}:{source['source_line']};{source['evidence']};commit={source['source_commit']}",
                "notes": f"path_prefix={source['path_prefix']};selected={source['selected']};no product-tree auto-materialization",
            }
        )

    engine = PRODUCT / "madomagi" / "engine_i18n.tsv"
    official_additions = {row["source_text"]: row for row in read_tsv(ENGINE_OFFICIAL)}
    livia_source = "カーテンコールで終いやな"
    seen_engine_sources: set[str] = set()
    data_line = 0
    for physical_line, raw in enumerate(engine.read_text(encoding="utf-8-sig").splitlines(), 1):
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split("\t")
        if len(parts) != 2:
            raise ValueError(f"malformed engine row {physical_line}: {raw!r}")
        data_line += 1
        ja, cn = parts
        if ja in seen_engine_sources:
            raise AssertionError(f"duplicate engine source key: {ja!r}")
        seen_engine_sources.add(ja)

        official = official_additions.get(ja)
        if official:
            if cn != official["current_cn"]:
                raise AssertionError(
                    f"engine official entry drift: {ja!r}: {cn!r} != {official['current_cn']!r}"
                )
            component = "engine_runtime_i18n_official"
            provenance_class = official["source_tier"]
            source_stage = "pass18_engine_official_additions"
            source_batch = "official-cn-engine-authority"
            source_author = "official CN game data; adoption recorded by HiiragiNemu"
            machine = official["is_machine_translation"]
            confidence = official["confidence"]
            authority_tier = official["source_tier"]
            authority_match = cn
            authority_status = "official-source-verified"
            issue_type = "official_engine_translation"
            suggestion = cn
            manual_status = official["manual_review_status"]
            evidence = (
                f"{relative_display(ENGINE_OFFICIAL)}#{official['entry_id']};"
                f"{official['evidence_path_or_key']};sha256={official['source_sha256']}"
            )
            notes = official["notes"]
        elif ja == livia_source:
            component = "engine_runtime_i18n_official"
            provenance_class = "official_cn_exact_stable_id"
            source_stage = "official-cn-recovery-livia"
            source_batch = "official-cn-stable-id"
            source_author = "official CN game data; historical adoption commit author retained in evidence"
            machine = "false"
            confidence = "exact-id-match"
            authority_tier = "official-cn"
            authority_match = cn
            authority_status = "official-source-verified"
            issue_type = "official_engine_translation"
            suggestion = cn
            manual_status = "official-source-verified"
            evidence = (
                "git-blame:7f80672146e8de6033416a371cad9a6d89ce24af:"
                "madomagi/engine_i18n.tsv;official-key=charaNo:1041/messageId:44/"
                "vo_char_1041_00_44_hca"
            )
            notes = "Official old-CN dump line recovered by stable character/message ID."
        elif ja == "上昇する" and cn == "":
            component = "engine_runtime_i18n_intentional_fragment"
            provenance_class = "intentional_cross_node_fragment_deletion"
            source_stage = "engine_i18n_structural_rule"
            source_batch = "documented-intentional-fragment"
            source_author = "existing maintenance rule; translator not applicable"
            machine = "false"
            confidence = "documented-structural"
            authority_tier = "intentional-structural-rule"
            authority_match = ""
            authority_status = "intentional-empty-not-untranslated"
            issue_type = "intentional_fragment_deletion"
            suggestion = ""
            manual_status = "documented-intentional"
            evidence = "i18n/README.md#跨节点语序片段；madomagi/engine_i18n.tsv"
            notes = "“提升”已并入上一片段；空目标用于删除重复的日文句尾。"
        else:
            component = "engine_runtime_i18n_unverified"
            provenance_class = "preexisting_engine_table_unknown"
            source_stage = "engine_i18n"
            source_batch = "preexisting-engine-table"
            source_author = "individual author not recorded"
            machine = "unknown"
            confidence = "low"
            authority_tier = "unknown"
            authority_match = ""
            authority_status = "requires_official_wiki_or_manual_check"
            issue_type = "engine_translation_unknown_provenance"
            suggestion = "needs-review/root-translation-required"
            manual_status = "needs-human-review"
            evidence = f"madomagi/engine_i18n.tsv:{physical_line}"
            notes = "与 scenario 剧情无关；随 JS 包分发；逐行作者/来源未记录"

        master.append(
            {
                "record_id": "",
                "component": component,
                "scope": "native_engine_i18n",
                "file": "madomagi/engine_i18n.tsv",
                "stable_key_or_line": str(physical_line),
                "field": "zhCN",
                "japanese_or_source_original": ja,
                "missing_original_reason": "",
                "current_cn": cn,
                "provenance_class": provenance_class,
                "source_stage": source_stage,
                "source_batch": source_batch,
                "source_author": source_author,
                "is_machine_translation": machine,
                "confidence": confidence,
                "runtime_consumed": "true; legacy client reads <files>/madomagi/engine_i18n.tsv",
                "highest_authority_tier": authority_tier,
                "highest_authority_match": authority_match,
                "authority_status": authority_status,
                "risk": "medium",
                "issue_type": issue_type,
                "suggested_cn": suggestion,
                "manual_review_status": manual_status,
                "review_status": manual_status,
                "evidence": evidence,
                "notes": notes,
            }
        )
        counts[component] += 1
    counts["engine_total"] = data_line
    if set(official_additions) - seen_engine_sources:
        raise AssertionError(
            f"official engine additions missing from runtime table: {sorted(set(official_additions) - seen_engine_sources)}"
        )
    return dict(counts)


def classify_frontend_empty_candidate(source: dict[str, str]) -> dict[str, str]:
    """Return the audited semantic state for one legacy-empty frontend row."""

    decision = FRONTEND_EMPTY_53_DECISIONS.get(source["key"])
    if decision is None:
        raise AssertionError(
            f"unclassified empty frontend candidate: {source['key']} "
            f"{source['source_text']!r}"
        )
    common = {
        "closure_status": decision,
        "is_machine_translation": "false; no translation was authored",
        "confidence": "exact-product-node-audit",
        "source_author": "not applicable; semantic classification only",
        "classification_evidence": (
            "semantic_product_hits_sha256="
            "a8d66dcdec688e4baa14071950764802ef696e0d6ea6133ab5709e5dff4c4959;"
            "closure_items_sha256="
            "5388304f6acf4a610303e335eda6b1e598e6842ded901b1a502f39d2aa05bfe3"
        ),
    }
    if decision == "runtime-absent/not-backlog":
        if source["candidate_cn"]:
            raise AssertionError(f"runtime-absent row unexpectedly has a candidate: {source['key']}")
        return {
            **common,
            "current_cn": "",
            "provenance_class": "current_product_exact_node_absence",
            "runtime_consumed": "false; exact source is absent from current runtime nodes",
            "highest_authority_tier": "current-product-exact-node-audit",
            "highest_authority_match": "",
            "authority_status": decision,
            "risk": "none",
            "issue_type": "frontend_source_absent_not_translation_backlog",
            "suggested_cn": "",
            "manual_review_status": decision,
            "notes": "Exact current-product source node does not exist; no runtime translation is required.",
        }
    if decision in {"visible-cn-compatible-identity", "identity-punctuation"}:
        if source["candidate_cn"] not in {"", source["source_text"]}:
            raise AssertionError(f"identity row candidate drift: {source['key']}")
        return {
            **common,
            "current_cn": source["candidate_cn"],
            "provenance_class": "current_product_visible_identity",
            "runtime_consumed": "visible exact runtime node; offline candidate remains unselected",
            "highest_authority_tier": "current-product-visible-identity-audit",
            "highest_authority_match": source["source_text"],
            "authority_status": decision,
            "risk": "low",
            "issue_type": "frontend_visible_identity_retain",
            "suggested_cn": source["source_text"],
            "manual_review_status": decision,
            "notes": "Retain the visible source spelling as the compatible identity; no product text was written.",
        }
    if decision != "official-cn-exact-path-dom-match":
        raise AssertionError(f"unsupported frontend empty classification: {decision}")
    if source["source_text"] != "属性相性" or source["candidate_cn"] not in {"", "属性克制"}:
        raise AssertionError("official frontend exact-path/DOM row drifted")
    return {
        **common,
        "current_cn": source["candidate_cn"],
        "provenance_class": "official_cn_exact_path_dom_match",
        "is_machine_translation": "false",
        "confidence": "exact-path-dom-match",
        "source_author": "official CN static product source",
        "classification_evidence": (
            "official-cn-static/magica/template/formation/FormationQuest.html;"
            "dom=#deckDetailCongeniality>p;sha256="
            "8a73978062da1662bb7405d93ca37ef4e924b8a0b14bd66a56237e6ea8480f8d"
        ),
        "runtime_consumed": "visible exact runtime node; offline candidate remains unselected",
        "highest_authority_tier": "official-cn-exact-path-dom-match",
        "highest_authority_match": "属性克制",
        "authority_status": "official-source-verified",
        "risk": "low",
        "issue_type": "frontend_official_cn_exact_path_dom_match",
        "suggested_cn": "属性克制",
        "manual_review_status": "official-source-verified",
        "notes": (
            "Official CN FormationQuest.html#deckDetailCongeniality uses 属性克制; "
            "source SHA256=8a73978062da1662bb7405d93ca37ef4e924b8a0b14bd66a56237e6ea8480f8d."
        ),
    }


def build_glossary_support_and_frontend_backlog() -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Return the Wiki glossary support layer and audited empty frontend rows.

    The glossary is authority evidence rather than an additional product-text
    review universe, so it is intentionally kept outside the master inventory.
    Empty frontend candidates are classified by the closed exact-node audit, not
    inferred from an empty offline maintenance field.
    """

    provenance_path = PRODUCT / "i18n" / "generated" / "input-provenance.tsv"
    provenance = read_tsv(provenance_path)
    glossary_rows: list[dict[str, str]] = []
    frontend_backlog: list[dict[str, str]] = []
    for source in provenance:
        source_file = source["source_file"]
        if source_file == "i18n/glossary.tsv":
            glossary_rows.append(
                {
                    "support_id": "",
                    "japanese_or_source_original": source["source_text"],
                    "authority_cn": source["candidate_cn"],
                    "authority_tier": "2_wiki",
                    "source_batch": source["source_batch"],
                    "source_author": "HiiragiNemu/magireco-wiki-data contributors",
                    "confidence": "high_as_wiki_candidate",
                    "runtime_consumed": "false; offline authority input, not directly consumed at runtime",
                    "manual_review_status": "authority-support-available",
                    "evidence": (
                        f"{relative_display(provenance_path)}:{source['source_line']};"
                        f"{source['evidence']};key={source['key']}"
                    ),
                    "notes": "Wiki is second authority; official CN still wins on an exact stable-ID conflict",
                }
            )
        elif source_file == "i18n/frontend-strings.tsv" and source["key"] in FRONTEND_EMPTY_53_DECISIONS:
            frontend_backlog.append(
                {
                    "backlog_id": "",
                    "file": source_file,
                    "stable_key_or_line": source["key"],
                    "scope": source["scope"],
                    "path_prefix": source["path_prefix"],
                    "japanese_or_source_original": source["source_text"],
                    "missing_original_reason": (
                        "extracted source string is retained; exact-node semantics are separately audited"
                    ),
                    "source_batch": source["source_batch"],
                    "evidence": (
                        f"{relative_display(provenance_path)}:{source['source_line']};"
                        f"{source['evidence']};candidate_id={source['candidate_id']};key={source['key']};"
                        "semantic_audit_sha256=a8d66dcdec688e4baa14071950764802ef696e0d6ea6133ab5709e5dff4c4959;"
                        "closure_items_sha256=5388304f6acf4a610303e335eda6b1e598e6842ded901b1a502f39d2aa05bfe3"
                    ),
                    **classify_frontend_empty_candidate(source),
                }
            )

    glossary_rows.sort(key=lambda r: (r["japanese_or_source_original"], r["authority_cn"]))
    frontend_backlog.sort(key=lambda r: (r["path_prefix"], r["japanese_or_source_original"]))
    for idx, row in enumerate(glossary_rows, 1):
        row["support_id"] = f"WGS-{idx:04d}"
    for idx, row in enumerate(frontend_backlog, 1):
        row["backlog_id"] = f"FUT-{idx:03d}"
    return glossary_rows, frontend_backlog


def append_support_universe(
    master: list[dict[str, str]],
    glossary_rows: list[dict[str, str]],
    frontend_backlog: list[dict[str, str]],
) -> None:
    """Put every migrated input row into the filterable all-source master."""

    for row in glossary_rows:
        master.append(
            {
                "record_id": "",
                "component": "glossary_wiki_authority_support",
                "scope": "offline_authority_support",
                "file": "i18n/glossary.tsv",
                "stable_key_or_line": row["support_id"],
                "field": "zhCN",
                "japanese_or_source_original": row["japanese_or_source_original"],
                "missing_original_reason": "",
                "current_cn": row["authority_cn"],
                "provenance_class": "wiki_authority_support",
                "source_stage": "migrated_glossary",
                "source_batch": row["source_batch"],
                "source_author": row["source_author"],
                "is_machine_translation": "false",
                "confidence": row["confidence"],
                "runtime_consumed": row["runtime_consumed"],
                "highest_authority_tier": "wiki",
                "highest_authority_match": row["authority_cn"],
                "authority_status": "wiki-authority-support-available",
                "risk": "low",
                "issue_type": "wiki_authority_support_not_direct_runtime",
                "suggested_cn": row["authority_cn"],
                "manual_review_status": row["manual_review_status"],
                "review_status": row["manual_review_status"],
                "evidence": row["evidence"],
                "notes": row["notes"],
            }
        )

    for row in frontend_backlog:
        master.append(
            {
                "record_id": "",
                "component": "frontend_untranslated",
                "scope": "frontend_i18n_input",
                "file": row["file"],
                "stable_key_or_line": row["stable_key_or_line"],
                "field": "candidate_cn",
                "japanese_or_source_original": row["japanese_or_source_original"],
                "missing_original_reason": row["missing_original_reason"],
                "current_cn": row["current_cn"],
                "provenance_class": row["provenance_class"],
                "source_stage": "migrated_frontend_input_exact_node_closure",
                "source_batch": row["source_batch"],
                "source_author": row["source_author"],
                "is_machine_translation": row["is_machine_translation"],
                "confidence": row["confidence"],
                "runtime_consumed": row["runtime_consumed"],
                "highest_authority_tier": row["highest_authority_tier"],
                "highest_authority_match": row["highest_authority_match"],
                "authority_status": row["authority_status"],
                "risk": row["risk"],
                "issue_type": row["issue_type"],
                "suggested_cn": row["suggested_cn"],
                "manual_review_status": row["manual_review_status"],
                "review_status": row["manual_review_status"],
                "evidence": f"{row['evidence']};{row['classification_evidence']}",
                "notes": row["notes"],
            }
        )


def append_battle_miss_review(master: list[dict[str, str]]) -> list[dict[str, str]]:
    """Add non-runtime battle misses without inventing or installing text."""

    memoria = read_json(WIKI_MEMORIA_EXTRACT)
    expected_wiki = {
        "旅する調整屋": {"number": 1449, "name_sc": "", "name_zh": "旅行的调整师"},
        "やさしいは作れる": {
            "number": 1472,
            "name_sc": "",
            "name_zh": "温柔可以学习掌握",
            "effect_max": "伤害上升状态[Ⅴ] & 伤害削减状态[Ⅳ]",
        },
    }
    for key, expected in expected_wiki.items():
        actual = memoria.get(key, {})
        for field, value in expected.items():
            if actual.get(field) != value:
                raise AssertionError(
                    f"bundled Wiki memoria drift: {key}/{field}: {actual.get(field)!r} != {value!r}"
                )

    rows = [
        {
            "battle_miss_id": "BM-NR-001",
            "original_text": "旅する調整屋",
            "candidate_cn": "旅行的调整师",
            "reference_location": "HiiragiNemu/magireco-wiki-data:data/memoria.json#/旅する調整屋/name_zh",
            "source_tier": "wiki-exact-piece-id-name_sc-empty",
            "evidence_path_or_key": f"{relative_display(WIKI_MEMORIA_EXTRACT)}#/旅する調整屋;number=1449;name_sc=empty;name_zh=旅行的调整师",
            "machine_translated": "unknown",
            "confidence": "wiki-exact-piece-id-name_sc-empty",
            "review_status": "needs-review/root-translation-required",
            "notes": "Candidate only; not inserted into engine/runtime. Simplified-Chinese field is empty in Wiki.",
        },
        {
            "battle_miss_id": "BM-NR-002",
            "original_text": "やさしいは作れる",
            "candidate_cn": "温柔可以学习掌握",
            "reference_location": "HiiragiNemu/magireco-wiki-data:data/memoria.json#/やさしいは作れる/name_zh",
            "source_tier": "wiki-exact-piece-id-name_sc-empty",
            "evidence_path_or_key": f"{relative_display(WIKI_MEMORIA_EXTRACT)}#/やさしいは作れる;number=1472;name_sc=empty;name_zh=温柔可以学习掌握",
            "machine_translated": "unknown",
            "confidence": "wiki-exact-piece-id-name_sc-empty",
            "review_status": "needs-review/root-translation-required",
            "notes": "Candidate only; not inserted into engine/runtime. Simplified-Chinese field is empty in Wiki.",
        },
        {
            "battle_miss_id": "BM-NR-003",
            "original_text": "Damage UP [V] / Reduce Damage [IV]",
            "candidate_cn": "伤害上升状态[Ⅴ] & 伤害削减状态[Ⅳ]",
            "reference_location": "HiiragiNemu/magireco-wiki-data:data/memoria.json#/やさしいは作れる/effect_max",
            "source_tier": "wiki-exact-piece-id;official-parallel-timed-art-only",
            "evidence_path_or_key": f"{relative_display(WIKI_MEMORIA_EXTRACT)}#/やさしいは作れる;number=1472;effect_max_ja=ダメージアップ状態[Ⅴ] & ダメージカット状態[Ⅳ];effect_max=伤害上升状态[Ⅴ] & 伤害削减状态[Ⅳ]",
            "machine_translated": "unknown",
            "confidence": "needs-context-review-parallel-art-not-exact-official",
            "review_status": "needs-review/root-translation-required",
            "notes": "Wiki candidate plus official-CN style evidence from a parallel timed art; no exact official art join. Candidate only; not inserted into engine/runtime.",
        },
    ]
    for source in rows:
        master.append(
            {
                "record_id": "",
                "component": "battle_miss_needs_review",
                "scope": "battle_miss_review",
                "file": source["reference_location"].split(":", 1)[-1].split("#", 1)[0],
                "stable_key_or_line": source["battle_miss_id"],
                "field": "candidate_cn",
                "japanese_or_source_original": source["original_text"],
                "missing_original_reason": "",
                "current_cn": source["candidate_cn"],
                "provenance_class": "wiki_candidate_not_runtime_applied",
                "source_stage": source["source_tier"],
                "source_batch": "battle-miss-needs-review",
                "source_author": "Wiki candidate; per-row machine/human authorship not proven",
                "is_machine_translation": "unknown",
                "confidence": source["confidence"],
                "runtime_consumed": "false; review candidate only",
                "highest_authority_tier": source["source_tier"],
                "highest_authority_match": source["candidate_cn"],
                "authority_status": "candidate-needs-root-review-not-runtime",
                "risk": "high",
                "issue_type": "battle_miss_candidate_not_closed",
                "suggested_cn": source["candidate_cn"],
                "manual_review_status": source["review_status"],
                "review_status": source["review_status"],
                "evidence": source["evidence_path_or_key"],
                "notes": source["notes"],
            }
        )
    return rows


def apply_pass18_inventory(
    master: list[dict[str, str]], dicts: Dictionaries
) -> list[dict[str, str]]:
    """Overlay all 939 Pass18 after-images and add targets outside pass15."""

    index: dict[tuple[str, str, str], dict[str, str]] = {}
    for row in master:
        if row["scope"] != "runtime_dictionary":
            continue
        key = (Path(row["file"]).name, row["stable_key_or_line"], row["field"])
        if key in index:
            raise AssertionError(f"duplicate runtime review target: {key}")
        index[key] = row

    applied: list[dict[str, str]] = []
    for correction in read_tsv(PASS18):
        filename = Path(correction["file"]).name
        target = (filename, correction["stable_key"], correction["field"])
        is_static = not correction["file"].startswith("magica/js/libs/")

        if is_static:
            product_path = PRODUCT / correction["file"]
            text = product_path.read_text(encoding="utf-8-sig")
            if correction["after"] not in text or correction["before"] in text:
                raise AssertionError(f"Pass18 static after-image mismatch: {correction['change_id']}")
            current = correction["after"]
        else:
            current = dicts.value(
                filename,
                correction["stable_key"],
                correction["field"],
                correction["after"],
            )
            if current != correction["after"]:
                raise AssertionError(
                    f"Pass18 runtime after-image mismatch {correction['change_id']}: "
                    f"{current!r} != {correction['after']!r}"
                )

        row = index.get(target)
        if row is None:
            row = {
                "record_id": "",
                "component": (
                    "static_pass18_authority_correction"
                    if is_static
                    else "runtime_pass18_outside_pass15"
                ),
                "scope": "static_js_html" if is_static else "runtime_dictionary",
                "file": correction["file"],
                "stable_key_or_line": correction["stable_key"],
                "field": correction["field"],
                "japanese_or_source_original": correction["before"],
                "missing_original_reason": (
                    "Pass18 records the replaced visible text; a Japanese source field is not available "
                    "in the pass15 residual universe"
                ),
                "current_cn": current,
                "runtime_consumed": "true; packaged JS/HTML" if is_static else "true; embedded runtime dictionary",
                "risk": risk_for(
                    correction["field"], current, "static_js_html" if is_static else "runtime_dictionary"
                ),
            }
            master.append(row)
            if not is_static:
                index[target] = row

        method = correction["translation_method"]
        root_personal = "root-personal-human" in method
        row.update(
            {
                "current_cn": current,
                "provenance_class": (
                    "pass18_root_personal_translation"
                    if root_personal
                    else "pass18_higher_authority_applied"
                ),
                "source_stage": correction["source_tier"],
                "source_batch": "pass18-authority-corrections",
                "source_author": (
                    "HiiragiNemu root-personal human translation/review"
                    if root_personal
                    else "official CN/Wiki authority adoption; no new model translation"
                ),
                "is_machine_translation": "false",
                "confidence": correction["confidence"],
                "highest_authority_tier": correction["source_tier"],
                "highest_authority_match": current,
                "authority_status": (
                    "root-translated-needs-human-review"
                    if correction["manual_review_status"] == "root-translated-needs-human-review"
                    else "pass18-authority-verified"
                ),
                "issue_type": (
                    "root_personal_translation_needs_human_review"
                    if correction["manual_review_status"] == "root-translated-needs-human-review"
                    else "historical_lower_authority_replaced"
                ),
                "suggested_cn": current,
                "manual_review_status": correction["manual_review_status"],
                "review_status": correction["manual_review_status"],
                "evidence": (
                    f"{relative_display(PASS18)}#{correction['change_id']};"
                    f"{correction['evidence']}"
                ),
                "notes": (
                    f"pass18_before={correction['before']};method={method};"
                    f"rules={correction['rules']};{correction['notes']}"
                ),
            }
        )
        applied.append(
            {
                **correction,
                "current_product_cn": current,
                "inventory_component": row["component"],
                "inventory_review_status": row["manual_review_status"],
            }
        )

    if len(applied) != 939:
        raise AssertionError(f"Pass18 manifest: expected 939, got {len(applied)}")
    return applied


def finalize_master(master: list[dict[str, str]]) -> None:
    master.sort(key=lambda r: (r["component"], r["file"], r["stable_key_or_line"], r["field"]))
    for idx, row in enumerate(master, 1):
        row["record_id"] = f"MT-{idx:05d}"
        finalize_review_columns(row)


def build_master(dicts: Dictionaries) -> tuple[list[dict[str, str]], list[dict[str, str]], dict[str, Any]]:
    residual_rows = read_tsv(RESIDUAL)
    overlays, static_checks = build_checklist_overlays(dicts)
    master: list[dict[str, str]] = []
    changed_rows: list[dict[str, str]] = []
    master_targets: set[tuple[str, str, str]] = set()
    changed_counts = Counter()

    for line_no, source in enumerate(residual_rows, 2):
        target = (source["file"], source["key"], source["field"])
        pass15 = str(json_scalar(source["release"]))
        original = str(json_scalar(source["baseline"]))
        current = dicts.value(source["file"], source["key"], source["field"], pass15)
        overlay = overlays.get(target)
        changed = current != pass15
        format_only = changed and normalized_linebreaks(current) == normalized_linebreaks(pass15)

        if changed:
            component = "runtime_changed_after_pass15"
            if overlay and authority_check(overlay):
                resolution_class = "higher_authority_applied"
                changed_counts[overlay["source_tier"]] += 1
            elif format_only:
                resolution_class = "linebreak_serialization_normalized"
                changed_counts[resolution_class] += 1
            elif overlay and overlay.get("source_tier", "").startswith("3_"):
                resolution_class = "manual_verified_without_higher_authority"
                changed_counts[resolution_class] += 1
            else:
                resolution_class = "changed_unclassified"
                changed_counts[resolution_class] += 1
            changed_rows.append(
                {
                    "file": source["file"],
                    "stable_key": source["key"],
                    "field": source["field"],
                    "japanese_original": original,
                    "pass15_cn": pass15,
                    "current_cn": current,
                    "authority_tier": overlay["source_tier"] if overlay and authority_check(overlay) else "",
                    "authority_source": overlay["source_path"] if overlay else "",
                    "resolution": resolution_class,
                }
            )
        else:
            component = "runtime_current_unverified"
            resolution_class = "unchanged_since_pass15"

        if overlay and authority_check(overlay) and changed:
            provenance = "pass8_llm_or_other_replaced_by_higher_authority"
            stage = overlay["source_tier"]
            authority_tier = overlay["source_tier"]
            authority_match = current
            authority_status = "higher_authority_applied"
            machine = "historical_llm_or_other_replaced"
            confidence = "high"
            manual_status = "authority-applied-pending-human-check"
            evidence = (
                f"{relative_display(RESIDUAL)}:{line_no};"
                f"{relative_display(RELEASE_CHECKLIST)};{overlay['source_path']}"
            )
        elif overlay and overlay.get("source_tier", "").startswith("3_"):
            provenance = "existing_manual_unverified"
            stage = overlay["source_tier"]
            authority_tier = "none_exact_found"
            authority_match = ""
            authority_status = "manual_without_higher_authority_pair"
            machine = "unknown_manual_or_model"
            confidence = "low"
            manual_status = "pending"
            evidence = (
                f"{relative_display(RESIDUAL)}:{line_no};"
                f"{relative_display(RELEASE_CHECKLIST)};{overlay['source_path']}"
            )
        else:
            provenance = "pass8_llm_or_other_unverified"
            stage = "pass15_remaining_residual"
            authority_tier = "none_exact_found"
            authority_match = ""
            authority_status = "official_dump_absent_and_no_closed_wiki_pair"
            machine = "unknown_llm_or_other; traditional_mt_not_proven"
            confidence = "low"
            manual_status = "pending"
            evidence = (
                f"{relative_display(RESIDUAL)}:{line_no};"
                f"{relative_display(PASS8_RECON)};"
                f"magica/js/libs/{source['file']}"
            )

        missing_reason = "" if original else "pass8 reconstructed provenance says baseline field absent"
        notes = (
            "llm_or_other 是历史来源桶，未证明使用传统机翻；"
            f"current_partition={resolution_class}"
        )
        if format_only:
            notes += ";仅换行序列化变化，语义来源仍需校验"
        row = {
            "record_id": "",
            "component": component,
            "scope": "runtime_dictionary",
            "file": f"magica/js/libs/{source['file']}",
            "stable_key_or_line": source["key"],
            "field": source["field"],
            "japanese_or_source_original": original,
            "missing_original_reason": missing_reason,
            "current_cn": current,
            "provenance_class": provenance,
            "source_stage": stage,
            "source_batch": "pass8-llm-or-other",
            "source_author": "individual translator/author not recorded in pass8 provenance",
            "is_machine_translation": machine,
            "confidence": confidence,
            "runtime_consumed": "true; embedded runtime dictionary",
            "highest_authority_tier": authority_tier,
            "highest_authority_match": authority_match,
            "authority_status": authority_status,
            "risk": risk_for(source["field"], current, "runtime_dictionary"),
            "issue_type": issue_for(source["field"], current),
            "suggested_cn": current if authority_status == "higher_authority_applied" else "needs-review/root-translation-required",
            "manual_review_status": manual_status,
            "review_status": "needs-human-review",
            "evidence": evidence,
            "notes": notes,
        }
        master.append(row)
        master_targets.add(target)

    # Manual JSON rows outside the original 8,959 residual universe.
    for target, check in overlays.items():
        if authority_check(check) or target in master_targets or not check.get("source_tier", "").startswith("3_"):
            continue
        filename, key, field = target
        current = dicts.value(filename, key, field, check["final_cn"])
        master.append(
            {
                "record_id": "",
                "component": "runtime_manual_outside_pass15",
                "scope": "runtime_dictionary",
                "file": f"magica/js/libs/{filename}",
                "stable_key_or_line": key,
                "field": field,
                "japanese_or_source_original": check["original_text"],
                "missing_original_reason": "source is a pre-change string rather than a guaranteed Japanese original",
                "current_cn": current,
                "provenance_class": "existing_manual_unverified",
                "source_stage": check["source_tier"],
                "source_batch": "pass16-manual-runtime",
                "source_author": "individual reviewer not recorded per row",
                "is_machine_translation": "unknown_manual_or_model",
                "confidence": "low",
                "runtime_consumed": "true; embedded runtime dictionary",
                "highest_authority_tier": "none_exact_found",
                "highest_authority_match": "",
                "authority_status": "manual_without_higher_authority_pair",
                "risk": risk_for(field, current, "runtime_dictionary", check["category"]),
                "issue_type": "unverified_manual_runtime_text",
                "suggested_cn": "needs-review/root-translation-required",
                "manual_review_status": "pending",
                "review_status": "needs-human-review",
                "evidence": f"{relative_display(RELEASE_CHECKLIST)};{check['source_path']}",
                "notes": check["notes"],
            }
        )
        master_targets.add(target)

    for check in static_checks:
        if authority_check(check) or not check.get("source_tier", "").startswith("3_"):
            continue
        master.append(
            {
                "record_id": "",
                "component": "static_js_html_unverified",
                "scope": "static_js_html",
                "file": check["file"],
                "stable_key_or_line": check["key_or_line"],
                "field": check["field"],
                "japanese_or_source_original": check["original_text"],
                "missing_original_reason": "source may be a pre-change Chinese/manual string, not always a Japanese original",
                "current_cn": check["final_cn"],
                "provenance_class": "static_manual_or_model_unverified",
                "source_stage": check["source_tier"],
                "source_batch": "pass16-static-manual-model-review",
                "source_author": "individual translator/reviewer not recorded per row",
                "is_machine_translation": "unknown_manual_or_model",
                "confidence": "low",
                "runtime_consumed": "true; packaged JS/HTML",
                "highest_authority_tier": "none_exact_found",
                "highest_authority_match": "",
                "authority_status": "no_per_row_official_or_wiki_pair",
                "risk": risk_for(check["field"], check["final_cn"], "static_js_html", check["category"]),
                "issue_type": "unverified_static_js_html_translation_or_review",
                "suggested_cn": "needs-review/root-translation-required",
                "manual_review_status": "pending",
                "review_status": "needs-human-review",
                "evidence": f"{relative_display(RELEASE_CHECKLIST)};{check['source_path']}",
                "notes": check["notes"],
            }
        )

    migrated_counts = append_migrated_i18n_and_engine(master)
    master.sort(key=lambda r: (r["component"], r["file"], r["stable_key_or_line"], r["field"]))
    for idx, row in enumerate(master, 1):
        row["record_id"] = f"MT-{idx:05d}"

    component_counts = Counter(r["component"] for r in master)
    meta = {
        "pass15_residual_rows": len(residual_rows),
        "runtime_current_unverified": component_counts["runtime_current_unverified"],
        "runtime_changed_after_pass15": component_counts["runtime_changed_after_pass15"],
        "runtime_manual_outside_pass15": component_counts["runtime_manual_outside_pass15"],
        "changed_after_pass15_breakdown": dict(sorted(changed_counts.items())),
        "component_counts": dict(sorted(component_counts.items())),
        "migrated_i18n_counts": migrated_counts,
    }
    return master, changed_rows, meta


# These are source-backed component/name locks, not newly authored translations.
NAME_RULES = [
    {
        "jp": "リヴィア・メディロス",
        "bad": r"莉薇娅·梅德洛斯",
        "authority": "莉薇娅·梅黛洛斯",
        "tier": "1_official_cn_dump",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/pass8_field_provenance_reconstructed.tsv.gz#/cardList.json/10414/cardName",
        "kind": "confirmed_official_name_mismatch",
    },
    {
        "jp": "コルボー",
        "bad": r"科尔博",
        "authority": "可鲁波",
        "tier": "1_official_cn_dump",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/pass8_field_provenance_reconstructed.tsv.gz#/cardList.json/40253/cardName",
        "kind": "confirmed_official_name_mismatch",
    },
    {
        "jp": "エリザ",
        "bad": r"伊莉莎",
        "authority": "爱丽莎",
        "tier": "1_official_cn_dump",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/pass8_field_provenance_reconstructed.tsv.gz#/cardList.json/40264/cardName",
        "kind": "confirmed_official_name_mismatch",
    },
    {
        "jp": "ミヌゥ",
        "bad": r"米努",
        "authority": "米诺",
        "tier": "1_official_cn_dump",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/pass8_field_provenance_reconstructed.tsv.gz#/pieceList.json/1375/description",
        "kind": "confirmed_official_name_mismatch",
    },
    {
        "jp": "アルティメットまどか",
        "bad": r"(?:终极|究极)小圆",
        "authority": "圆神",
        "tier": "1_official_cn_dump",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/pass8_field_provenance_reconstructed.tsv.gz#/itemList.json/EVENT_DAILYTOWER_1056_STICKER_210100/parameter",
        "kind": "confirmed_official_name_mismatch",
    },
    {
        "jp": "万年桜のウワサ",
        "bad": r"万年樱之传闻",
        "authority": "万年樱的传闻",
        "tier": "1_official_cn_dump_component",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/pass8_field_provenance_reconstructed.tsv.gz#/itemList.json/EVENT_DAILYTOWER_1056_STICKER_304300/parameter",
        "kind": "confirmed_official_component_mismatch",
    },
    {
        "jp": "ユゥ",
        "bad": r"(?:[,，]悠(?:$|[）)]))|优(?:的|……|$)",
        "authority": "夕",
        "tier": "2_wiki",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/wiki_characters.json.gz#/夕",
        "kind": "confirmed_wiki_name_and_internal_consistency_mismatch",
    },
    {
        "jp": "シィ",
        "bad": r"(?:[,，]希(?:$|[）)]))|希的试炼",
        "authority": "椎",
        "tier": "2_wiki",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/wiki_characters.json.gz#/椎",
        "kind": "confirmed_wiki_name_and_internal_consistency_mismatch",
    },
    {
        "jp": "ウワサのみこと",
        "bad": r"传闻(?:御琴|命)",
        "authority": "谣命",
        "tier": "2_wiki",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/wiki_characters.json.gz#/谣命",
        "kind": "confirmed_wiki_name_mismatch",
    },
    {
        "jp": "くろ",
        "bad": r"[,，]黑$",
        "authority": "小黑",
        "tier": "2_wiki",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/wiki_characters.json.gz#/小黑",
        "kind": "confirmed_wiki_name_mismatch",
    },
    {
        "jp": "フェリシアちゃん",
        "bad": r"^菲莉希亚的 Doppel$",
        "authority": "小菲莉希亚",
        "tier": "2_wiki",
        "evidence": "magica/i18n_audit/release_v26_authority/machine_translation_review/inputs/wiki_characters.json.gz#/小菲莉希亚",
        "kind": "confirmed_wiki_variant_name_mismatch",
    },
]


# Existing official CN character components that legitimately override later Wiki
# literal transliterations.  These aliases prevent false positives in the generic
# Wiki scan; they do not create new output text.
OFFICIAL_COMPONENT_ALIASES = {
    "いろはちゃん": ["小彩羽", "彩羽"],
    "まどか・いろは": ["小圆·彩羽"],
    "無限大いろはちゃん": ["无限大小彩羽"],
    "∞いろは": ["∞彩羽"],
    "いろは・黒江": ["彩羽·黑江"],
    "まどか先輩・いろはちゃん": ["小圆前辈·小彩羽"],
    "万年桜のウワサ": ["万年樱的传闻"],
}


def normalize_ascii_case(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().casefold()


def wiki_name_maps() -> list[dict[str, Any]]:
    data = read_json(WIKI_CHARACTERS)
    result = []
    for slug, record in data.items():
        info = record.get("infobox", {}) or {}
        ja = (record.get("nameJa") or info.get("日文名") or "").strip()
        zh = (record.get("nameZh") or info.get("中文名") or "").strip()
        if not ja or not zh:
            continue
        core = re.sub(r"[\s・·（）()\[\]【】_\-]", "", ja)
        if len(core) < 2:
            continue
        aliases = [zh]
        for field in ("中文名", "其他译名"):
            value = info.get(field, "")
            if value:
                aliases.extend(x.strip() for x in re.split(r"[，,、/；;]", value) if x.strip())
        aliases.extend(OFFICIAL_COMPONENT_ALIASES.get(ja, []))
        result.append(
            {
                "ja": ja,
                "zh": zh,
                "slug": slug,
                "aliases": list(dict.fromkeys(aliases)),
                "evidence": f"{relative_display(WIKI_CHARACTERS)}#/{slug}",
            }
        )
    return sorted(result, key=lambda x: (-len(x["ja"]), x["ja"]))


def longest_nonoverlap_name_hits(text: str, mappings: list[dict[str, Any]]) -> list[dict[str, Any]]:
    candidates = []
    for mapping in mappings:
        start = text.find(mapping["ja"])
        while start >= 0:
            candidates.append((start, start + len(mapping["ja"]), mapping))
            start = text.find(mapping["ja"], start + 1)
    candidates.sort(key=lambda x: (x[0], -(x[1] - x[0])))
    selected = []
    occupied: list[tuple[int, int]] = []
    for start, end, mapping in candidates:
        if any(not (end <= a or start >= b) for a, b in occupied):
            continue
        selected.append(mapping)
        occupied.append((start, end))
    return selected


def alias_present(current: str, aliases: list[str]) -> bool:
    folded = normalize_ascii_case(current)
    for alias in aliases:
        if not alias:
            continue
        if re.search(r"[A-Za-z]", alias):
            if normalize_ascii_case(alias) in folded:
                return True
        elif alias in current:
            return True
    return False


def build_name_candidates(master: list[dict[str, str]]) -> list[dict[str, str]]:
    by_record: dict[str, dict[str, str]] = {}
    manual_records: set[str] = set()

    for row in master:
        if row["scope"] != "runtime_dictionary":
            continue
        original = row["japanese_or_source_original"]
        current = row["current_cn"]
        for rule in NAME_RULES:
            if rule["jp"] in original and re.search(rule["bad"], current):
                candidate = {
                    "record_id": row["record_id"],
                    "file": row["file"],
                    "stable_key": row["stable_key_or_line"],
                    "field": row["field"],
                    "japanese_original": original,
                    "current_cn": current,
                    "authority_japanese_term": rule["jp"],
                    "authority_cn": rule["authority"],
                    "authority_tier": rule["tier"],
                    "status": "confirmed_current_mismatch",
                    "risk": "critical",
                    "issue_type": rule["kind"],
                    "suggested_cn": rule["authority"],
                    "evidence": rule["evidence"],
                    "notes": "权威中文仅作为专名/组件候选；完整句由根任务按上下文处理",
                }
                by_record[row["record_id"]] = candidate
                manual_records.add(row["record_id"])
                row["highest_authority_tier"] = rule["tier"]
                row["highest_authority_match"] = rule["authority"]
                row["authority_status"] = "current_conflicts_with_higher_authority"
                row["risk"] = "critical"
                row["issue_type"] = rule["kind"]
                row["suggested_cn"] = rule["authority"]
                row["notes"] += ";已命中确定专名错译/不一致规则"
                break

    mappings = wiki_name_maps()
    for row in master:
        if row["scope"] != "runtime_dictionary" or row["record_id"] in manual_records:
            continue
        original = row["japanese_or_source_original"]
        current = row["current_cn"]
        if not isinstance(original, str) or not isinstance(current, str):
            continue
        for mapping in longest_nonoverlap_name_hits(original, mappings):
            if alias_present(current, mapping["aliases"]):
                continue
            candidate = {
                "record_id": row["record_id"],
                "file": row["file"],
                "stable_key": row["stable_key_or_line"],
                "field": row["field"],
                "japanese_original": original,
                "current_cn": current,
                "authority_japanese_term": mapping["ja"],
                "authority_cn": mapping["zh"],
                "authority_tier": "2_wiki",
                "status": "needs_context_review",
                "risk": "high" if row["field"] in {"name", "title", "parameter", "charaName", "cardName"} else "medium",
                "issue_type": "wiki_primary_or_alias_not_observed_in_current_cn",
                "suggested_cn": mapping["zh"],
                "evidence": mapping["evidence"],
                "notes": "自动最长专名匹配；可能存在官方组件、组织英文名或语境省略，需人工确认后才可替换",
            }
            by_record.setdefault(row["record_id"], candidate)
            if row["highest_authority_tier"] == "none_exact_found":
                row["highest_authority_tier"] = "2_wiki_candidate"
                row["highest_authority_match"] = mapping["zh"]
                row["authority_status"] = "wiki_name_candidate_requires_context_review"
            break

    return sorted(by_record.values(), key=lambda r: (r["status"], r["file"], r["stable_key"], r["field"]))


def build_explicit_llm_history(dicts: Dictionaries) -> list[dict[str, str]]:
    explicit = [r for r in read_tsv(PASS8_PROV) if r["category"].startswith("LLM")]
    doppel = {(r["doppel_id"], r["field"]): r for r in read_tsv(PASS9_DOPPEL)}
    applied = {(r["file"], r["key"], r["field"]): r for r in read_tsv(PASS9_APPLIED)}
    rows = []
    for idx, source in enumerate(explicit, 1):
        current = dicts.value(source["target"], source["key"], source["field"], source["after"])
        d = doppel.get((source["key"], source["field"]))
        a = applied.get((source["target"], source["key"], source["field"]))
        if d:
            authority_cn = d["expected_wiki"]
            exact_or_spacing_equivalent = re.sub(r"\s+", "", current) == re.sub(r"\s+", "", authority_cn)
            official_term_equivalent = re.sub(
                r"\s+", "", re.sub(r"doppel", "魔女化身", current, flags=re.IGNORECASE)
            ) == re.sub(
                r"\s+", "", re.sub(r"doppel", "魔女化身", authority_cn, flags=re.IGNORECASE)
            )
            if exact_or_spacing_equivalent:
                status = "resolved_to_wiki_or_wiki_equivalent"
            elif official_term_equivalent:
                status = "resolved_to_wiki_plus_official_cn_term"
            else:
                status = "current_drift_from_wiki"
            evidence = f"{relative_display(PASS9_DOPPEL)}#/{source['key']}/{source['field']}"
            resolution = (
                f"{d['status']};Pass18 official-cn Doppel->魔女化身"
                if official_term_equivalent and not exact_or_spacing_equivalent
                else d["status"]
            )
        elif a:
            authority_cn = a["after"]
            status = "resolved_by_wiki_context_fix" if current == authority_cn else "current_drift_from_wiki_context_fix"
            evidence = f"{relative_display(PASS9_APPLIED)}#/{source['target']}/{source['key']}/{source['field']}"
            resolution = a["method"]
        else:
            authority_cn = ""
            status = "still_unverified"
            evidence = relative_display(PASS8_PROV)
            resolution = ""
        rows.append(
            {
                "history_id": f"LLM-{idx:03d}",
                "file": f"magica/js/libs/{source['target']}",
                "stable_key": source["key"],
                "field": source["field"],
                "japanese_or_before": source["before"],
                "pass8_llm_cn": source["after"],
                "current_cn": current,
                "wiki_authority_cn": authority_cn,
                "status": status,
                "resolution_method": resolution,
                "evidence": evidence,
            }
        )
    return rows


def build_unique(master: list[dict[str, str]]) -> list[dict[str, str]]:
    grouped: dict[tuple[str, str, str, str], list[dict[str, str]]] = defaultdict(list)
    for row in master:
        key = (
            row["scope"],
            row["japanese_or_source_original"],
            row["current_cn"],
            row["provenance_class"],
        )
        grouped[key].append(row)
    result = []
    for idx, (key, rows) in enumerate(sorted(grouped.items(), key=lambda x: (x[0][0], x[0][1], x[0][2])), 1):
        scope, original, current, provenance = key
        risks = {"low": 1, "medium": 2, "high": 3, "critical": 4}
        risk = max((r["risk"] for r in rows), key=lambda x: risks.get(x, 0))
        result.append(
            {
                "unique_id": f"MTU-{idx:05d}",
                "scope": scope,
                "japanese_or_source_original": original,
                "current_cn": current,
                "occurrences": str(len(rows)),
                "provenance_class": provenance,
                "max_risk": risk,
                "authority_statuses": ";".join(sorted({r["authority_status"] for r in rows})),
                "authority_matches": ";".join(sorted({r["highest_authority_match"] for r in rows if r["highest_authority_match"]})),
                "sample_locations": ";".join(
                    f"{r['file']}#{r['stable_key_or_line']}/{r['field']}" for r in rows[:5]
                ),
                "review_status": "needs-human-review",
                "suggested_cn": next(
                    (r["suggested_cn"] for r in rows if r["suggested_cn"] != "needs-review/root-translation-required"),
                    "needs-review/root-translation-required",
                ),
            }
        )
    return result


def main() -> None:
    HERE.mkdir(parents=True, exist_ok=True)
    for stale in HERE.iterdir():
        if stale.is_file():
            stale.unlink()
    source_snapshot = read_json(SOURCE_SNAPSHOT)
    for source in source_snapshot["sources"]:
        bundled = BUNDLED_INPUTS / source["bundled_file"]
        if sha256(bundled) != source["sha256"]:
            raise AssertionError(f"bundled input hash drift: {bundled}")
    pass18_baseline = read_json(PASS18_BASELINE)
    if pass18_baseline["baseline_head"] != "d5e8f75d93f6760a588e592c22a3754d19370c68":
        raise AssertionError("unexpected Pass18 baseline commit")
    dicts = Dictionaries(LIBS)

    legacy_battle_decisions = read_tsv(LEGACY_BATTLE_DECISIONS)
    legacy_battle_inventory = read_tsv(LEGACY_BATTLE_INVENTORY)
    if (len(legacy_battle_decisions), len(legacy_battle_inventory)) != (8, 20):
        raise AssertionError("legacy battle inventory must remain 8 decisions / 20 unique misses")
    detailed_sources = {
        row["detailed_translation_row"]
        for row in legacy_battle_inventory
        if row["detailed_translation_row"]
    }
    decision_sources = {row["source_text"] for row in legacy_battle_decisions}
    if detailed_sources != decision_sources:
        raise AssertionError("legacy battle inventory and decision table no longer align")
    if sum(row["action"].startswith(("translate-", "review-"))
           for row in legacy_battle_inventory) != 7:
        raise AssertionError("legacy battle actionable miss count drifted")
    if sum(row["current_candidate_machine_translation"] == "unknown"
           for row in legacy_battle_decisions) != 4:
        raise AssertionError("legacy battle unknown-provenance candidate count drifted")

    master, changed_rows, legacy_meta = build_master(dicts)
    glossary_support, frontend_untranslated = build_glossary_support_and_frontend_backlog()
    pass18_applied = apply_pass18_inventory(master, dicts)
    append_support_universe(master, glossary_support, frontend_untranslated)
    battle_miss_rows = append_battle_miss_review(master)

    # Make the historical changed partition explicitly explain every Pass18 row.
    p18 = pass18_index()
    for row in changed_rows:
        correction = p18.get((Path(row["file"]).name, row["stable_key"], row["field"]))
        if correction:
            row["authority_tier"] = correction["source_tier"]
            row["authority_source"] = f"{relative_display(PASS18)}#{correction['change_id']}"
            row["resolution"] = (
                "pass18_root_personal_translation"
                if correction["manual_review_status"] == "root-translated-needs-human-review"
                else "pass18_authority_applied"
            )

    finalize_master(master)
    name_candidates = build_name_candidates(master)
    # build_name_candidates enriches authority/risk metadata; refresh canonical columns.
    for row in master:
        finalize_review_columns(row)
    explicit_history = build_explicit_llm_history(dicts)
    unique = build_unique(master)

    runtime_rows = [r for r in master if r["scope"] == "runtime_dictionary"]
    static_rows = [r for r in master if r["scope"] == "static_js_html"]
    frontend_rows = [
        r
        for r in master
        if r["component"] in {"frontend_ai_assisted_translated", "frontend_untranslated"}
    ]
    glossary_master = [r for r in master if r["component"] == "glossary_wiki_authority_support"]
    override_fragment_rows = [
        r
        for r in master
        if r["component"] in {"overrides_unverified_mixed", "fragments_unverified_mixed"}
    ]
    engine_rows = [r for r in master if r["scope"] == "native_engine_i18n"]
    battle_miss_master = [r for r in master if r["component"] == "battle_miss_needs_review"]
    pass18_master = [
        r for r in master if r.get("source_batch") == "pass18-authority-corrections"
    ]
    proper_name_review = [
        r
        for r in master
        if r["scope"] == "runtime_dictionary"
        and (
            r["field"]
            in {"name", "title", "charaName", "cardName", "pieceName", "parameter", "kana", "school"}
            or "name" in r["issue_type"]
            or "organization" in r["issue_type"]
        )
    ]

    component_counts = Counter(r["component"] for r in master)
    scope_counts = Counter(r["scope"] for r in master)
    source_bucket_counts = Counter(r["source_bucket"] for r in master)
    source_tier_counts = Counter(r["source_tier"] for r in master)
    machine_counts = Counter(r["machine_translated"] for r in master)
    review_counts = Counter(r["review_status"] for r in master)
    risk_counts = Counter(r["risk"] for r in master)
    llm_status = Counter(r["status"] for r in explicit_history)
    changed_breakdown = Counter(r["resolution"] for r in changed_rows)
    engine_component_counts = Counter(r["component"] for r in engine_rows)
    frontend_empty_partition = Counter(r["manual_review_status"] for r in frontend_untranslated)

    expected = {
        "master": 12930,
        "runtime": 9665,
        "static": 303,
        "frontend": 1685,
        "frontend_empty": 53,
        "glossary": 955,
        "overrides_fragments": 16,
        "engine": 303,
        "battle_miss_needs_review": 3,
        "battle_runtime_language_decisions": 8,
        "battle_runtime_unique_misses": 20,
        "pass18": 939,
        "explicit_llm_history": 264,
    }
    actual = {
        "master": len(master),
        "runtime": len(runtime_rows),
        "static": len(static_rows),
        "frontend": len(frontend_rows),
        "frontend_empty": len(frontend_untranslated),
        "glossary": len(glossary_master),
        "overrides_fragments": len(override_fragment_rows),
        "engine": len(engine_rows),
        "battle_miss_needs_review": len(battle_miss_master),
        "battle_runtime_language_decisions": len(legacy_battle_decisions),
        "battle_runtime_unique_misses": len(legacy_battle_inventory),
        "pass18": len(pass18_applied),
        "explicit_llm_history": len(explicit_history),
    }
    if actual != expected:
        raise AssertionError(f"review universe counts drifted: expected={expected}, actual={actual}")
    expected_frontend_empty_partition = Counter(
        {
            "runtime-absent/not-backlog": 18,
            "visible-cn-compatible-identity": 33,
            "identity-punctuation": 1,
            "official-source-verified": 1,
        }
    )
    if frontend_empty_partition != expected_frontend_empty_partition:
        raise AssertionError(
            "frontend empty-53 classification drifted: "
            f"{dict(frontend_empty_partition)}"
        )
    if engine_component_counts != Counter(
        {
            "engine_runtime_i18n_unverified": 296,
            "engine_runtime_i18n_official": 6,
            "engine_runtime_i18n_intentional_fragment": 1,
        }
    ):
        raise AssertionError(f"engine provenance partition drifted: {engine_component_counts}")
    if any("drift" in status for status in llm_status):
        raise AssertionError(f"explicit pass8 LLM history drift remains: {dict(llm_status)}")
    if sum(r["review_status"] == "root-translated-needs-human-review" for r in pass18_master) != 12:
        raise AssertionError("Pass18 root-personal review queue must contain exactly 12 fields")
    if len({r["record_id"] for r in master}) != len(master):
        raise AssertionError("master record ids are not unique")

    resolved_fields = [
        "file",
        "stable_key",
        "field",
        "japanese_original",
        "pass15_cn",
        "current_cn",
        "authority_tier",
        "authority_source",
        "resolution",
    ]
    name_fields = [
        "record_id",
        "file",
        "stable_key",
        "field",
        "japanese_original",
        "current_cn",
        "authority_japanese_term",
        "authority_cn",
        "authority_tier",
        "status",
        "risk",
        "issue_type",
        "suggested_cn",
        "evidence",
        "notes",
    ]
    history_fields = [
        "history_id",
        "file",
        "stable_key",
        "field",
        "japanese_or_before",
        "pass8_llm_cn",
        "current_cn",
        "wiki_authority_cn",
        "status",
        "resolution_method",
        "evidence",
    ]
    unique_fields = [
        "unique_id",
        "scope",
        "japanese_or_source_original",
        "current_cn",
        "occurrences",
        "provenance_class",
        "max_risk",
        "authority_statuses",
        "authority_matches",
        "sample_locations",
        "review_status",
        "suggested_cn",
    ]
    pass18_fields = list(pass18_applied[0].keys())

    outputs: list[Path] = []

    def emit_tsv(name: str, rows: list[dict[str, Any]], fields: list[str]) -> None:
        path = HERE / name
        write_tsv(path, rows, fields)
        outputs.append(path)

    def emit_json(name: str, value: Any) -> None:
        path = HERE / name
        write_json(path, value)
        outputs.append(path)

    emit_tsv("full_machine_translation_review.tsv", master, MASTER_FIELDS)
    emit_json("full_machine_translation_review.json", master)
    emit_tsv("unique_text_review.tsv", unique, unique_fields)
    emit_json("unique_text_review.json", unique)
    emit_tsv("runtime_translation_review.tsv", runtime_rows, MASTER_FIELDS)
    emit_tsv("static_js_html_review.tsv", static_rows, MASTER_FIELDS)
    emit_tsv("frontend_all_1685.tsv", frontend_rows, MASTER_FIELDS)
    emit_tsv("frontend_untranslated_53.tsv", [r for r in frontend_rows if r["component"] == "frontend_untranslated"], MASTER_FIELDS)
    emit_tsv("glossary_wiki_955.tsv", glossary_master, MASTER_FIELDS)
    emit_tsv("overrides_fragments_16.tsv", override_fragment_rows, MASTER_FIELDS)
    emit_tsv("engine_i18n_review_303.tsv", engine_rows, MASTER_FIELDS)
    emit_tsv("battle_miss_needs_review.tsv", battle_miss_rows, list(battle_miss_rows[0].keys()))
    emit_tsv(
        "battle_runtime_language_decisions_8.tsv",
        legacy_battle_decisions,
        list(legacy_battle_decisions[0].keys()),
    )
    emit_tsv(
        "battle_runtime_unique_misses_20.tsv",
        legacy_battle_inventory,
        list(legacy_battle_inventory[0].keys()),
    )
    emit_tsv("pass18_authority_corrections_939.tsv", pass18_applied, pass18_fields)
    emit_tsv("runtime_changed_after_pass15.tsv", changed_rows, resolved_fields)
    emit_tsv("proper_name_priority_review.tsv", proper_name_review, MASTER_FIELDS)
    emit_tsv("authority_name_candidates.tsv", name_candidates, name_fields)
    emit_json("authority_name_candidates.json", name_candidates)
    emit_tsv("explicit_llm_history_264.tsv", explicit_history, history_fields)
    emit_json("explicit_llm_history_264.json", explicit_history)

    dictionary_hashes = {p.name: sha256(p) for p in sorted(LIBS.glob("*.json"))}
    input_paths = [
        PASS8_RECON,
        PASS8_PROV,
        RESIDUAL,
        PASS9_DOPPEL,
        PASS9_APPLIED,
        RELEASE_CHECKLIST,
        PASS18,
        PASS18_BASELINE,
        ENGINE_OFFICIAL,
        WIKI_CHARACTERS,
        WIKI_MEMORIA_EXTRACT,
        LEGACY_BATTLE_DECISIONS,
        LEGACY_BATTLE_INVENTORY,
        SOURCE_SNAPSHOT,
        PRODUCT / "i18n" / "generated" / "input-provenance.tsv",
        PRODUCT / "i18n" / "migration-source-summary.json",
        PRODUCT / "i18n" / "frontend-strings.tsv",
        PRODUCT / "i18n" / "glossary.tsv",
        PRODUCT / "i18n" / "overrides.tsv",
        PRODUCT / "i18n" / "fragments.tsv",
        PRODUCT / "madomagi" / "engine_i18n.tsv",
    ]
    missing_inputs = [str(p) for p in input_paths if not p.is_file()]
    if missing_inputs:
        raise FileNotFoundError(f"missing review inputs: {missing_inputs}")
    product_file_count, product_content_sha256 = product_content_snapshot()

    summary = {
        "schema": "magireco-cn-v26-machine-translation-review/v2",
        "generated_at": AUDIT_EPOCH,
        "generator": "tools/build-v26-machine-review.py",
        "product_text_modified_by_generator": False,
        "authority_order": [
            "official-cn",
            "wiki",
            "existing-human",
            "new-root-human-or-llm",
        ],
        "snapshot": {
            "baseline_head": pass18_baseline["baseline_head"],
            "baseline_commit_epoch": AUDIT_EPOCH,
            "product_content_file_count": product_file_count,
            "product_content_sha256": product_content_sha256,
            "wiki_head": source_snapshot["wiki_head"],
            "runtime_dictionary_count": len(dictionary_hashes),
            "runtime_dictionary_sha256": dictionary_hashes,
            "engine_i18n_sha256": sha256(PRODUCT / "madomagi" / "engine_i18n.tsv"),
        },
        "counts": {
            **actual,
            "unique_text_pairs": len(unique),
            "proper_name_priority_rows": len(proper_name_review),
            "authority_name_candidates": len(name_candidates),
            "by_component": dict(sorted(component_counts.items())),
            "by_scope": dict(sorted(scope_counts.items())),
            "by_source_bucket": dict(sorted(source_bucket_counts.items())),
            "by_source_tier": dict(sorted(source_tier_counts.items())),
            "by_machine_translation": dict(sorted(machine_counts.items())),
            "by_review_status": dict(sorted(review_counts.items())),
            "by_risk": dict(sorted(risk_counts.items())),
            "frontend_empty_53_partition": dict(sorted(frontend_empty_partition.items())),
            "engine_partition": dict(sorted(engine_component_counts.items())),
            "runtime_changed_after_pass15": len(changed_rows),
            "runtime_changed_resolution": dict(sorted(changed_breakdown.items())),
            "explicit_llm_status": dict(sorted(llm_status.items())),
            "pass18_root_personal_needs_review": 12,
        },
        "coverage_contract": {
            "runtime_residual_and_non_residual": len(runtime_rows),
            "static_js_html": len(static_rows),
            "frontend_all_including_empty": len(frontend_rows),
            "glossary_wiki_support": len(glossary_master),
            "overrides_and_fragments": len(override_fragment_rows),
            "engine_runtime": len(engine_rows),
            "battle_miss_candidate_only": len(battle_miss_master),
            "battle_runtime_language_decisions": len(legacy_battle_decisions),
            "battle_runtime_unique_misses": len(legacy_battle_inventory),
            "explicit_pass8_llm_history": len(explicit_history),
            "filter_column": "source_bucket",
            "filter_values": ["official", "wiki", "legacy-ai", "new-root-human", "unknown"],
        },
        "interpretation": {
            "machine_translation_flag": "Describes the current candidate provenance. Unknown and AI-assisted remain explicit rather than being relabeled as human-reviewed.",
            "untranslated_policy": "The generator writes no product text. The historic empty-53 cohort follows exact evidence: 18 runtime-absent/not-backlog, 33 visible-cn-compatible-identity, one identity-punctuation, and 属性相性 resolved by an official-CN exact path/DOM match to 属性克制.",
            "pass18_policy": "All 939 after-images are read from the manifest and verified against the current product before inclusion.",
            "explicit_llm_doppel": "Wiki-equivalent text further normalized by the stronger official-cn term Doppel->魔女化身 is recorded as resolved, not drift.",
            "engine_policy": "Six official mappings are separated from one documented intentional empty fragment and 296 unknown-provenance entries: four exact stable-ID mappings (existing Livia plus three Mitama), one exact-art-ID join, and one official-UI identity retain.",
            "battle_runtime_policy": "The complete observed set is preserved as 20 unique misses: seven actionable rows, one official retained term, and twelve already-CN or nonlinguistic rows. Four captured current candidates have unknown provenance; after the official exact-art join is applied, three Wiki/parallel-art candidates remain machineTranslated=unknown and review-only.",
            "offline_tables": "frontend/glossary/overrides/fragments are maintenance inputs; only engine_i18n.tsv is directly consumed by the native client.",
        },
        "legacy_build_meta": legacy_meta,
        "inputs": {relative_display(path): sha256(path) for path in input_paths},
    }
    emit_json("summary.json", summary)

    readme = f"""# v26 全套机翻／LLM 人工校对清单

本目录由 `tools/build-v26-machine-review.py` 可复现生成；生成器只读取产品与审计证据，不创建或改写中文译文。
`inputs/` 固化了 pass8 与 Wiki 的最小必要来源快照，干净检出不依赖其他本地仓库／工作树。

## 总览

- 全量统一主表：**{len(master):,}** 行（`full_machine_translation_review.tsv`）
- runtime residual／非 residual：**{len(runtime_rows):,}**
- static JS／HTML：**{len(static_rows):,}**
- frontend：**{len(frontend_rows):,}**（含 **{len(frontend_untranslated)}** 条空候选）
- Wiki glossary 支撑层：**{len(glossary_master):,}**
- overrides／fragments：**{len(override_fragment_rows):,}**
- engine runtime：**{len(engine_rows):,}**（官方 6：稳定 ID 4、art-ID 拼接 1、官方 UI 原样保留 1；结构性空项 1；来源未知 296）
- battle miss 候选但未进入 runtime：**{len(battle_miss_master):,}**
- battle runtime 全量采样：**{len(legacy_battle_inventory):,}** 个唯一 miss，含 **{len(legacy_battle_decisions):,}** 条语言决策；7 条 actionable、1 条国服原样保留、12 条中文／非语言项
- Pass18：**{len(pass18_applied):,}**，其中 **12** 条 root 亲译仍待人工复核
- pass8 明确 LLM 历史：**{len(explicit_history):,}**

## 筛选

统一主表可按 `source_bucket` 筛选：`official`、`wiki`、`legacy-ai`、`new-root-human`、`unknown`。每行均含原文、当前中文、建议中文、产品／引用位置、来源层级、证据、是否机翻、置信度与复核状态。

frontend 历史空候选 53 条按精确证据闭合：18 条 `runtime-absent/not-backlog`、33 条 `visible-cn-compatible-identity`、1 条 `identity-punctuation`；“属性相性”由国服同路径同 DOM 节点精确命中“属性克制”，状态为 `official-source-verified`。生成器没有写入产品译文。

## 子表

- `runtime_translation_review.tsv`：运行时 23 字典的 residual 与非 residual 全集。
- `static_js_html_review.tsv`：静态 JS／HTML。
- `frontend_all_1685.tsv`：四表中的 frontend 全量，含空候选。
- `glossary_wiki_955.tsv`：Wiki 第二权威支撑层。
- `overrides_fragments_16.tsv`：路径／跨节点混合来源补丁。
- `engine_i18n_review_303.tsv`：native 直接读取的 engine 表。
- `battle_miss_needs_review.tsv`：仅供根任务复核、未进入 runtime 的候选。
- `battle_runtime_language_decisions_8.tsv`：实战 8 条语言决策的来源／机翻状态。
- `battle_runtime_unique_misses_20.tsv`：持久日志 20 个唯一 miss 的无遗漏分类。
- `pass18_authority_corrections_939.tsv`：Pass18 before／after 与最终产品复核。
- `explicit_llm_history_264.tsv`：pass8 明确 LLM 历史。
- `proper_name_priority_review.tsv`：专名优先人工校对视图。
- `SHA256SUMS.txt`：所有产物及生成器哈希。
"""
    readme_path = HERE / "README.md"
    readme_path.write_text(readme, encoding="utf-8", newline="\n")
    outputs.append(readme_path)

    sums_lines = [f"{sha256(path)}  {path.name}\n" for path in sorted(outputs, key=lambda p: p.name)]
    sums_lines.extend(
        f"{sha256(path)}  inputs/{path.name}\n" for path in sorted(BUNDLED_INPUTS.iterdir()) if path.is_file()
    )
    sums_lines.append(f"{sha256(Path(__file__))}  ../../../../tools/build-v26-machine-review.py\n")
    (HERE / "SHA256SUMS.txt").write_text("".join(sums_lines), encoding="utf-8", newline="\n")

    print(json.dumps({"output": str(HERE), "counts": actual}, ensure_ascii=False))


if __name__ == "__main__":
    main()
